### ISSUE TITLE
@steps screenplay

### ISSUE THREAD

**Issue by hanymorcos** [serenity-bdd/bdd-trader#2]
I'm trying to use @steps with screenplay but I'm getting a different instance class of the shared steps. 

I appreciate any feedback or example. 

thanks,

Hany

**Comment by wakaleo** [comment]
Could you give an example of what you are trying to do and how you are using the @steps annotation?

**Comment by hanymorcos** [comment]
[serenity_steps.zip](https://github.com/serenity-bdd/bdd-trader/files/2535561/serenity_steps.zip)

Attaching is a sample file with CommonStepDefintion class. The application attempts to do a get and a post to postman-echo.com.  When attempting to use the getter method to retrieve values for the common steps, I always get Null value.  The serenity.properties file contains "pass.through.session" variable that I use for now to pass variables through Serenity session hash.  If you have some time download and run the example.

**Comment by hanymorcos** [comment]
I moved the common @Given step to a common step class and I'm attempting to inject that file into other steps using the @steps annotation.  The @Given gherkin step pass value and that value is maintained in the state of the class instance. But I might be mixing @Given and @Step when using @Steps annotation. I guess the question should be can I split @Given step into separate classes and maintain the class state between these two classes using @Steps.  The @Given is being called but the @Steps is passing a different instance than instance being called. 

Thanks,

H

**Comment by hanymorcos** [comment]
@Steps only would link classes with @Step definition annotation and not with @Given annotation. I was getting duplicate step exception from Cucumber that's why I split the steps up.

**Comment by hanymorcos** [comment]
I'm looking into Serenity Pico-container support.

**Comment by hanymorcos** [comment]
https://groups.google.com/forum/#!topic/thucydides-users/T4LcZsX9_VM
I attempted to use the pico container and a steps base class that will have the variables. It's not working for me. I saw that you mentioned on a different post that the serenity framework is a dependency injection.  How inject a state class between cucumber annotated classes? I'm attaching the sample with pico container.

thanks,

H
[serenity_steps 2.zip](https://github.com/serenity-bdd/bdd-trader/files/2535881/serenity_steps.2.zip)

**Comment by wakaleo** [comment]
I have no knowledge of the serenity pick module. The @given and @steps annotations are quite separate, so you can’t really inject Cucumber step definition classes into Serenity step libraries. They way to share state is to use shares @steps libraries.

**Comment by hanymorcos** [comment]
[serenity_steps 4.zip](https://github.com/serenity-bdd/bdd-trader/files/2535948/serenity_steps.4.zip)

I got it to work. I separated out a state class and then used @steps to injected into the split classes of Cucumber steps.  It works for me when I set the @steps annotation attribute to true.
